#!/bin/bash

source oop.sh

class enemy
  func setHealth
  func setType
  var health
  var eType

enemy::setType()
{
  types=("beast" "humanoid" "abstract" "enigma" "undead" "monster" "chimera")
  sizes=("small" "medium" "large" "gigantic" "massive" "mysterious")
  prefix=("common" "uncommon" "rare" "epic" "unreal" "LEGENDARY")
  RANDOM=$$$(date +%s)

  eType=${sizes[$RANDOM % ${#sizes[@]} ] }+" "+${prefix[$RANDOM % {#prefix[@]}]}+" "+${types[$RANDOM % ${#types[@]}]}
}

enemy::setHealth()
{
  case $eType in
     *"common"*)
      case $eType in
        "small"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%45+65))
                ;;
              *"humanoid")
                health=$(($RANDOM%70+95))
                ;;
              *"abstract")
                health=$(($RANDOM%120+200))
                ;;
              *"enigma")
                health=$(($RANDOM%1+800))
                ;;
              *"undead")
                health=$(($RANDOM%90+100))
                ;;
              *"monster")
                health=$(($RANDOM%110+150))
                ;;
              *"chimera")
                health=$(($RANDOM%45+200))
                ;;
            esac
        "medium"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%95+125))
              ;;
            *"humanoid")
              health=$(($RANDOM%100+140))
              ;;
            *"abstract")
              health=$(($RANDOM%240+380))
              ;;
            *"enigma")
              health=$(($RANDOM%1+1900))
              ;;
            *"undead")
              health=$(($RANDOM%140+160))
              ;;
            *"monster")
              health=$(($RANDOM%200+260))
              ;;
            *"chimera")
              health=$(($RANDOM%95+380))
              ;;
          esac
        "large"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%140+200))
              ;;
            *"humanoid")
              health=$(($RANDOM%155+225))
              ;;
            *"abstract")
              health=$(($RANDOM%450+660))
              ;;
            *"enigma")
              health=$(($RANDOM%1+3000))
              ;;
            *"undead")
              health=$(($RANDOM%200+225))
              ;;
            *"monster")
              health=$(($RANDOM%400+510))
              ;;
            *"chimera")
              health=$(($RANDOM%155+660))
              ;;
          esac
        "gigantic"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%300+500))
              ;;
            *"humanoid")
              health=$(($RANDOM%450+700))
              ;;
            *"abstract")
              health=$(($RANDOM%1200+2100))
              ;;
            *"enigma")
              health=$(($RANDOM%1+15000))
              ;;
            *"undead")
              health=$(($RANDOM%600+720))
              ;;
            *"monster")
              health=$(($RANDOM%980+1325))
              ;;
            *"chimera")
              health=$(($RANDOM%300+2100))
              ;;
          esac
          "massive"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%700+1800))
                ;;
              *"humanoid")
                health=$(($RANDOM%1200+2000))
                ;;
              *"abstract")
                health=$(($RANDOM%3000+4900))
                ;;
              *"enigma")
                health=$(($RANDOM%1+32500))
                ;;
              *"undead")
                health=$(($RANDOM%2000+2100))
                ;;
              *"monster")
                health=$(($RANDOM%1950+2400))
                ;;
              *"chimera")
                health=$(($RANDOM%700+4900))
                ;;
            esac
          "mysterious"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%5000+15000))
                ;;
              *"humanoid")
                health=$(($RANDOM%10000+22125))
                ;;
              *"abstract")
                health=$(($RANDOM%30000+47500))
                ;;
              *"enigma")
                health=$(($RANDOM%1+100000))
                ;;
              *"undead")
                health=$(($RANDOM%12500+15000))
                ;;
              *"monster")
                health=$(($RANDOM%20000+27900))
                ;;
              *"chimera")
                health=$(($RANDOM%5000+47500))
                ;;
            esac
        esac
    *"uncommon"*)
      case $eType in
        "small"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%55+85))
              ;;
            *"humanoid")
              health=$(($RANDOM%90+135))
              ;;
            *"abstract")
              health=$(($RANDOM%200+340))
              ;;
            *"enigma")
              health=$(($RANDOM%100+800))
              ;;
            *"undead")
              health=$(($RANDOM%120+145))
              ;;
            *"monster")
              health=$(($RANDOM%130+180))
              ;;
            *"chimera")
              health=$(($RANDOM%55+340))
              ;;
          esac
        "medium"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%140+215))
              ;;
            *"humanoid")
              health=$(($RANDOM%210+255))
              ;;
            *"abstract")
              health=$(($RANDOM%300+640))
              ;;
            *"enigma")
              health=$(($RANDOM%100+3000))
              ;;
            *"undead")
              health=$(($RANDOM%230+255))
              ;;
            *"monster")
              health=$(($RANDOM%200+290))
              ;;
            *"chimera")
              health=$(($RANDOM%140+640))
              ;;
          esac
        "large"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%200+320))
              ;;
            *"humanoid")
              health=$(($RANDOM%250+380))
              ;;
            *"abstract")
              health=$(($RANDOM%500+1100))
              ;;
            *"enigma")
              health=$(($RANDOM%100+5500))
              ;;
            *"undead")
              health=$(($RANDOM%350+370))
              ;;
            *"monster")
              health=$(($RANDOM%300+410))
              ;;
            *"chimera")
              health=$(($RANDOM%200+1100))
              ;;
          esac
        "gigantic"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%700+1300))
              ;;
            *"humanoid")
              health=$(($RANDOM%800+1550))
              ;;
            *"abstract")
              health=$(($RANDOM%2000+4500))
              ;;
            *"enigma")
              health=$(($RANDOM%100+29000))
              ;;
            *"undead")
              health=$(($RANDOM%900+1100))
              ;;
            *"monster")
              health=$(($RANDOM%1300+1600))
              ;;
            *"chimera")
              health=$(($RANDOM%700+4500))
              ;;
          esac
        "massive"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%2000+3200))
              ;;
            *"humanoid")
              health=$(($RANDOM%2400+3600))
              ;;
            *"abstract")
              health=$(($RANDOM%4300+9000))
              ;;
            *"enigma")
              health=$(($RANDOM%100+40000))
              ;;
            *"undead")
              health=$(($RANDOM%2200+2350))
              ;;
            *"monster")
              health=$(($RANDOM%2600+3200))
              ;;
            *"chimera")
              health=$(($RANDOM%2000+9000))
              ;;
          esac
        "mysterious"*)
          case $eType in
            *"beast")
              health=$(($RANDOM%12000+25600))
              ;;
            *"humanoid")
              health=$(($RANDOM%26200+49000))
              ;;
            *"abstract")
              health=$(($RANDOM%57000+100000))
              ;;
            *"enigma")
              health=$(($RANDOM%100+1000000))
              ;;
            *"undead")
              health=$(($RANDOM%48000+50000))
              ;;
            *"monster")
              health=$(($RANDOM%39000+60000))
              ;;
            *"chimera")
              health=$(($RANDOM%12000+100000))
              ;;
          esac
        esac
      *" rare"*)
        case $eType in
          "small"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%110+190))
                ;;
              *"humanoid")
                health=$(($RANDOM%200+335))
                ;;
              *"abstract")
                health=$(($RANDOM%450+700))
                ;;
              *"enigma")
                health=$(($RANDOM%500+2100))
                ;;
              *"undead")
                health=$(($RANDOM%220+235))
                ;;
              *"monster")
                health=$(($RANDOM%300+420))
                ;;
              *"chimera")
                health=$(($RANDOM%110+700))
                ;;
            esac
          "medium"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%230+400))
                ;;
              *"humanoid")
                health=$(($RANDOM%355+410))
                ;;
              *"abstract")
                health=$(($RANDOM%710+1300))
                ;;
              *"enigma")
                health=$(($RANDOM%500+6000))
                ;;
              *"undead")
                health=$(($RANDOM%400+415))
                ;;
              *"monster")
                health=$(($RANDOM%390+580))
                ;;
              *"chimera")
                health=$(($RANDOM%230+1300))
                ;;
            esac
          "large"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%360+700))
                ;;
              *"humanoid")
                health=$(($RANDOM%510+890))
                ;;
              *"abstract")
                health=$(($RANDOM%1400+5000))
                ;;
              *"enigma")
                health=$(($RANDOM%500+15000))
                ;;
              *"undead")
                health=$(($RANDOM%600+630))
                ;;
              *"monster")
                health=$(($RANDOM%560+800))
                ;;
              *"chimera")
                health=$(($RANDOM%360+5000))
                ;;
            esac
          "gigantic"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%1200+3000))
                ;;
              *"humanoid")
                health=$(($RANDOM%1555+4780))
                ;;
              *"abstract")
                health=$(($RANDOM%4000+27500))
                ;;
              *"enigma")
                health=$(($RANDOM%500+200000))
                ;;
              *"undead")
                health=$(($RANDOM%3200+3700))
                ;;
              *"monster")
                health=$(($RANDOM%2500+4900))
                ;;
              *"chimera")
                health=$(($RANDOM%1200+27500))
                ;;
            esac
          "massive"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%8000+21000))
                ;;
              *"humanoid")
                health=$(($RANDOM%14500+36200))
                ;;
              *"abstract")
                health=$(($RANDOM%35000+150000))
                ;;
              *"enigma")
                health=$(($RANDOM%500+1250000))
                ;;
              *"undead")
                health=$(($RANDOM%36000+42000))
                ;;
              *"monster")
                health=$(($RANDOM%29000+51250))
                ;;
              *"chimera")
                health=$(($RANDOM%8000+150000))
                ;;
            esac
          "mysterious"*)
            case $eType in
              *"beast")
                health=$(($RANDOM%40000+97000))
                ;;
              *"humanoid")
                health=$(($RANDOM%43500+133000))
                ;;
              *"abstract")
                health=$(($RANDOM%90000+825000))
                ;;
              *"enigma")
                health=$(($RANDOM%500+7500000))
                ;;
              *"undead")
                health=$(($RANDOM%68500+75000))
                ;;
              *"monster")
                health=$(($RANDOM%55000+105000))
                ;;
              *"chimera")
                health=$(($RANDOM%40000+825000))
                ;;
            esac
          esac
      *"epic"*
          case $eType in
            "small"*)
              case $eType in
                *"beast")
                  health=$(($RANDOM%300+550))
                  ;;
                *"humanoid")
                  health=$(($RANDOM%390+710))
                  ;;
                *"abstract")
                  health=$(($RANDOM%600+1900))
                  ;;
                *"enigma")
                  health=$(($RANDOM%1000+15000))
                  ;;
                *"undead")
                  health=$(($RANDOM%450+510))
                  ;;
                *"monster")
                  health=$(($RANDOM%420+865))
                  ;;
                *"chimera")
                  health=$(($RANDOM%300+1900))
                  ;;
              esac
            "medium"*)
              case $eType in
                *"beast")
                  health=$(($RANDOM%230+400))
                  ;;
                *"humanoid")
                  health=$(($RANDOM%355+410))
                  ;;
                *"abstract")
                  health=$(($RANDOM%710+1300))
                  ;;
                *"enigma")
                  health=$(($RANDOM%500+6000))
                  ;;
                *"undead")
                  health=$(($RANDOM%400+415))
                  ;;
                *"monster")
                  health=$(($RANDOM%390+580))
                  ;;
                *"chimera")
                  health=$(($RANDOM%230+1300))
                  ;;
              esac
            "large"*)
              case $eType in
                *"beast")
                  health=$(($RANDOM%360+700))
                  ;;
                *"humanoid")
                  health=$(($RANDOM%510+890))
                  ;;
                *"abstract")
                  health=$(($RANDOM%1400+5000))
                  ;;
                *"enigma")
                  health=$(($RANDOM%500+15000))
                  ;;
                *"undead")
                  health=$(($RANDOM%600+630))
                  ;;
                *"monster")
                  health=$(($RANDOM%560+800))
                  ;;
                *"chimera")
                  health=$(($RANDOM%360+5000))
                  ;;
              esac
            "gigantic"*)
              case $eType in
                *"beast")
                  health=$(($RANDOM%1200+3000))
                  ;;
                *"humanoid")
                  health=$(($RANDOM%1555+4780))
                  ;;
                *"abstract")
                  health=$(($RANDOM%4000+27500))
                  ;;
                *"enigma")
                  health=$(($RANDOM%500+200000))
                  ;;
                *"undead")
                  health=$(($RANDOM%3200+3700))
                  ;;
                *"monster")
                  health=$(($RANDOM%2500+4900))
                  ;;
                *"chimera")
                  health=$(($RANDOM%1200+27500))
                  ;;
              esac
            "massive"*)
              case $eType in
                *"beast")
                  health=$(($RANDOM%8000+21000))
                  ;;
                *"humanoid")
                  health=$(($RANDOM%14500+36200))
                  ;;
                *"abstract")
                  health=$(($RANDOM%35000+150000))
                  ;;
                *"enigma")
                  health=$(($RANDOM%500+1250000))
                  ;;
                *"undead")
                  health=$(($RANDOM%36000+42000))
                  ;;
                *"monster")
                  health=$(($RANDOM%29000+51250))
                  ;;
                *"chimera")
                  health=$(($RANDOM%8000+150000))
                  ;;
              esac
            "mysterious"*)
              case $eType in
                *"beast")
                  health=$(($RANDOM%40000+97000))
                  ;;
                *"humanoid")
                  health=$(($RANDOM%43500+133000))
                  ;;
                *"abstract")
                  health=$(($RANDOM%90000+825000))
                  ;;
                *"enigma")
                  health=$(($RANDOM%500+7500000))
                  ;;
                *"undead")
                  health=$(($RANDOM%68500+75000))
                  ;;
                *"monster")
                  health=$(($RANDOM%55000+105000))
                  ;;
                *"chimera")
                  health=$(($RANDOM%40000+825000))
                  ;;
              esac
            esac
}
